In [1]:
import sklearn

In [2]:
sklearn.__version__

'0.24.2'

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [5]:
import pandas as pd

In [7]:
iris = load_iris()

In [8]:
# 딕셔너리는 아니지만 딕셔너리처럼 사용가능하다.
type(iris)

sklearn.utils.Bunch

In [9]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [10]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
# array가 아니라 dataframe식으로 사용할 수 있다.
iris = load_iris(as_frame = True)

In [15]:
type(iris)

sklearn.utils.Bunch

In [16]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [17]:
iris['data']

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [18]:
iris_df = iris['data']
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [19]:
iris_df['target'] = iris['target']
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [20]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [21]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

##### 데이터 세트 분리

In [23]:
# train_test_split() : 분리할 떄 사용
# 매개변수의 이름앞에 *가 붙어있으면 리스트형태로 여러개가 올 수 있다. **두개인 경우에는 딕셔너리 형태
# test_size = 데이터를 몇프로를 쓸것인지 정하는 것 train_size와 합쳐서 100프로
# random_state = 0 : 패턴
# shuffle = True : 섞으려면 true, 안섞으려면 false
# stratify : 타겟값을 넣으면 됨.

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 0)

In [24]:
X_train, X_test, y_train, y_test

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
 137                6.4               3.1                5.5               1.8   
 84                 5.4               3.0                4.5               1.5   
 27                 5.2               3.5                1.5               0.2   
 127                6.1               3.0                4.9               1.8   
 132                6.4               2.8                5.6               2.2   
 ..                 ...               ...                ...               ...   
 9                  4.9               3.1                1.5               0.1   
 103                6.3               2.9                5.6               1.8   
 67                 5.8               2.7                4.1               1.0   
 117                7.7               3.8                6.7               2.2   
 47                 4.6               3.2                1.4               0.2   
 
      target  

In [25]:
type(X_train)

pandas.core.frame.DataFrame

In [26]:
dt_clf = DecisionTreeClassifier(random_state = 11)

##### 모델 학습

In [28]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

##### 검증

In [30]:
# 답을 주지않고 예측해보기
pred = dt_clf.predict(X_test)

In [31]:
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [161]:
y_test

136    2
61     1
125    2
107    2
95     1
103    2
91     1
18     0
140    2
144    2
55     1
132    2
106    2
101    2
37     0
127    2
94     1
32     0
139    2
96     1
86     1
117    2
12     0
1      0
28     0
65     1
108    2
42     0
8      0
112    2
Name: target, dtype: int32

In [33]:
# 학습결과가 맞는지 확인해보는 함수 matrics는 평가에 해당하는것은 다 들어있음
from sklearn.metrics import accuracy_score

In [34]:
# 테스트값이랑 예측값을 넣어주고 몇퍼센트 맞았는지 확인해줌
accuracy_score(y_test,pred)

1.0

##### Random state값 없이 해보기

In [155]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2)

In [156]:
dt_clf = DecisionTreeClassifier()

In [157]:
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [158]:
pred = dt_clf.predict(X_test)

In [159]:
from sklearn.metrics import accuracy_score

In [160]:
accuracy_score(y_test,pred)

1.0

##### 함수는 하나의 값을 내보내지만 여러가지의 값으로 분해할 수도 있다.

In [172]:
def test(a,b):
    '''
    이 함수는 결과값이 3개로 나갑니다.
    이렇게 함수안에 함수에 대한 설명을 적어두면
    나중에 함수안에서 shift + tab 버튼으로 docstring으로 내용을 확인할 수 있다.
    '''
    return a+b,a-b,a*b

In [ ]:
test()

In [164]:
result = test(1,2)
result

(3, -1, 2)

In [165]:
r1,r2,r3 = test(3,4)

In [166]:
r1,r2,r3

(7, -1, 12)

In [167]:
r1

7

In [168]:
r2

-1

In [169]:
r3

12

### 과적합 참조
![과적합](과적합.png)

```
print('hellow')
```

##### 검증율을 높이기 위해서 교차검증을 한다 KFold

In [173]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [174]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [178]:
# 셀을 합치고 싶을때 위에있는 셀에 커서를 두고 shift + m을 누르면 아래에 있는 셀과 합쳐진다.
kfold = KFold(n_splits = 5)

In [179]:
# 셀을 분리하고 싶을때에는 분리하고자 하는 부분에 커서를 두고 ctrl + shift + -를 누르면 분리된다.
cv_accuracy = []

In [182]:
iris.data.shape

(150, 4)

In [186]:
# 데이터 셔플을 하지 않아서 균일하게 나오지 않음.
n_iter = 0
for train_index, test_index in kfold.split(iris.data): # 인덱스 값을 뽑아준다.
    # print(train_index)
    # print('-'*50)
    # print(test_index)
    # print()
    X_train, X_test = iris.data[train_index],iris.data[test_index]
    # print(X_train,X_test)
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 : {X_train.shape[0]}, 검증데이터 건수 : {X_test.shape[0]}')
    print(f'정확도 : {accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 1.0
2번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9666666666666667
3번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.8666666666666667
4번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9333333333333333
5번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.7333333333333333
0.9


##### 데이터 셔플을 한것

In [ ]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [188]:
kfold = KFold(n_splits = 5, shuffle = True)

In [189]:
cv_accuracy = []

In [191]:
n_iter = 0
for train_index, test_index in kfold.split(iris.data): # 인덱스 값을 뽑아준다.
    # print(train_index)
    # print('-'*50)
    # print(test_index)
    # print()
    X_train, X_test = iris.data[train_index],iris.data[test_index]
    # print(X_train,X_test)
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 : {X_train.shape[0]}, 검증데이터 건수 : {X_test.shape[0]}')
    print(f'정확도 : {accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9
2번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9666666666666667
3번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.8333333333333334
4번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9
5번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 1.0
0.9333333333333333


##### 편중이 심한 데이터는 StratifiedKFold 를 사용한다

In [203]:
kfold = KFold(n_splits = 5, shuffle = True)

In [204]:
n_iter = 0
for train_index, test_index in kfold.split(iris.data): # 인덱스 값을 뽑아준다.
    X_train, X_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    # print(type(pd.Series(y_train)))
    print('학습용데이터 분포 :\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포 :\n',pd.Series(y_test).value_counts())

학습용데이터 분포 :
 0    41
2    40
1    39
dtype: int64
검증용데이터 분포 :
 1    11
2    10
0     9
dtype: int64
학습용데이터 분포 :
 2    41
0    40
1    39
dtype: int64
검증용데이터 분포 :
 1    11
0    10
2     9
dtype: int64
학습용데이터 분포 :
 1    43
0    39
2    38
dtype: int64
검증용데이터 분포 :
 2    12
0    11
1     7
dtype: int64
학습용데이터 분포 :
 1    44
2    40
0    36
dtype: int64
검증용데이터 분포 :
 0    14
2    10
1     6
dtype: int64
학습용데이터 분포 :
 0    44
2    41
1    35
dtype: int64
검증용데이터 분포 :
 1    15
2     9
0     6
dtype: int64


In [205]:
from sklearn.model_selection import StratifiedKFold

In [209]:
skfold = StratifiedKFold(n_splits = 5, shuffle = False)
n_iter = 0
for train_index, test_index in skfold.split(iris.data,iris.target): # 인덱스 값을 뽑아준다.
    X_train, X_test = iris.data[train_index],iris.data[test_index]
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    # print(type(pd.Series(y_train)))
    print('학습용데이터 분포 :\n',pd.Series(y_train).value_counts())
    print('검증용데이터 분포 :\n',pd.Series(y_test).value_counts())

학습용데이터 분포 :
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포 :
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포 :
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포 :
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포 :
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포 :
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포 :
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포 :
 0    10
1    10
2    10
dtype: int64
학습용데이터 분포 :
 0    40
1    40
2    40
dtype: int64
검증용데이터 분포 :
 0    10
1    10
2    10
dtype: int64


In [ ]:
skfold = StratifiedKFold(n_splits = 5, shuffle = True)
n_iter = 0
cv_accuracy = []
for train_index, test_index in skfold.split(iris.data,iris.target): # 인덱스 값을 뽑아준다.
    # print(train_index)
    # print('-'*50)
    # print(test_index)
    # print()
    X_train, X_test = iris.data[train_index],iris.data[test_index]
    # print(X_train,X_test)
    y_train, y_test = iris.target[train_index],iris.target[test_index]
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    accuracy = accuracy_score(y_test,pred)
    cv_accuracy.append(accuracy)
    n_iter += 1
    print(f'{n_iter}번째 교차검증')
    print(f'학습데이터 건수 : {X_train.shape[0]}, 검증데이터 건수 : {X_test.shape[0]}')
    print(f'정확도 : {accuracy}')
print(np.mean(cv_accuracy))

1번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9
2번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9333333333333333
3번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9333333333333333
4번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9666666666666667
5번째 교차검증
학습데이터 건수 : 120, 검증데이터 건수 : 30
정확도 : 0.9666666666666667
0.9400000000000001


### 2022-06-09일 수업

#### 교차 검증을 간단하게 - cross_val_score()

In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [2]:
iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

In [7]:
# scoring : 점수를 어떻게 매길거냐
# cv : 교차검증을 몇번을 할거냐
# 결과는 어레이의 형태로 정확도가 나옴

scores = cross_val_score(dt_clf,iris_data.data,iris_data.target,scoring = 'accuracy',cv = 3)
scores

array([0.98, 0.94, 0.98])

In [8]:
import numpy as np
print('교차 검증별 정확도', scores)
print('평균 교차 검증 정확도', np.mean(scores))

교차 검증별 정확도 [0.98 0.94 0.98]
평균 교차 검증 정확도 0.9666666666666667


#### 교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에 - CridSearchCV
#### 하이퍼 파라미터는 우리가 넣어줘야 하는 값

In [15]:
from sklearn.model_selection import GridSearchCV, train_test_split
import pandas as pd

In [10]:
grid_param = {'max_depth' : [1, 2, 3], 'min_samples_split' : [2, 3]}

In [13]:
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size = 0.2, random_state = 121) # 데이터 분리
dtree = DecisionTreeClassifier() # estimator
grid_dtree = GridSearchCV(dtree, param_grid = grid_param, cv = 3, refit = True) #객체생성
grid_dtree.fit(X_train,y_train) # 학습

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [14]:
# 함수는 () 인스턴스는 필요없음.
grid_dtree.cv_results_

{'mean_fit_time': array([0.00033243, 0.00097775, 0.        , 0.00033061, 0.00032942,
        0.        ]),
 'std_fit_time': array([4.70134046e-04, 5.47916812e-05, 0.00000000e+00, 4.67549039e-04,
        4.65863166e-04, 0.00000000e+00]),
 'mean_score_time': array([0.        , 0.        , 0.00067465, 0.        , 0.00066797,
        0.        ]),
 'std_score_time': array([0.        , 0.        , 0.00047798, 0.        , 0.00047233,
        0.        ]),
 'param_max_depth': masked_array(data=[1, 1, 2, 2, 3, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_min_samples_split': masked_array(data=[2, 3, 2, 3, 2, 3],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'max_depth': 1, 'min_samples_split': 2},
  {'max_depth': 1, 'min_samples_split': 3},
  {'max_depth': 2, 'min_samples_split': 2},
  {'max_depth': 2, 'min_samples_split': 3},
  {'ma

In [21]:
score_df = pd.DataFrame(grid_dtree.cv_results_)
score_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.000332      0.000470         0.000000        0.000000   
1       0.000978      0.000055         0.000000        0.000000   
2       0.000000      0.000000         0.000675        0.000478   
3       0.000331      0.000468         0.000000        0.000000   
4       0.000329      0.000466         0.000668        0.000472   
5       0.000000      0.000000         0.000000        0.000000   

  param_max_depth param_min_samples_split  \
0               1                       2   
1               1                       3   
2               2                       2   
3               2                       3   
4               3                       2   
5               3                       3   

                                     params  split0_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}              0.700   
1  {'max_depth': 1, 'min_samples_split': 3}              0.700   
2  {'max_depth': 2, 'min_samples_split': 2}              0.925   
3  {'max_depth': 2, 'min_samples_split': 3}              0.925   
4  {'max_depth': 3, 'min_samples_split': 2}              0.975   
5  {'max_depth': 3, 'min_samples_split': 3}              0.975   

   split1_test_score  split2_test_score  mean_test_score  std_test_score  \
0                0.7               0.70         0.700000    1.110223e-16   
1                0.7               0.70         0.700000    1.110223e-16   
2                1.0               0.95         0.958333    3.118048e-02   
3                1.0               0.95         0.958333    3.118048e-02   
4                1.0               0.95         0.975000    2.041241e-02   
5                1.0               0.95         0.975000    2.041241e-02   

   rank_test_score  
0                5  
1                5  
2                3  
3                3  
4                1  
5                1

In [22]:
score_df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [24]:
score_df[['params','mean_test_score', 'rank_test_score', 'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [25]:
grid_dtree.best_score_

0.975

In [26]:
grid_dtree.best_index_

4

In [28]:
# 학습된 모델
grid_dtree.best_estimator_

DecisionTreeClassifier(max_depth=3)

In [32]:
# 예측
pred = grid_dtree.best_estimator_.predict(X_test)
pred

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [33]:
# 정확도
from sklearn.metrics import accuracy_score

In [34]:
print('best estimator 정확도', accuracy_score(y_test,pred))

best estimator 정확도 0.9666666666666667


#### 레이블 인코딩 : 글자를 숫자로 변환해준다.

In [35]:
from sklearn.preprocessing import LabelEncoder

In [37]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [40]:
encoder = LabelEncoder() # 객체생성
encoder.fit(items) # 목록작성
labels = encoder.transform(items) 

In [41]:
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [42]:
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U5')

In [43]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U5')

#### 원 핫 인코딩 : 해당하는 컬럼에만 1로 표시하고 나머지는 0으로 바꾸는 방식

In [45]:
from sklearn.preprocessing import OneHotEncoder

In [44]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']
items

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [59]:
encoder = LabelEncoder()
labels = encoder.fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2], dtype=int64)

In [60]:
# 듀플은 ()안에 ,가 꼭 들어간다. ()없이 , , , 만들어가도 튜플이다. 튜플안에 데이터가 하나일 때에도 ,를 찍어서 표시해준다.
labels.shape

(8,)

In [65]:
labels = labels.reshape(-1,1)
labels.shape

(8, 1)

In [66]:
oh_encoder = OneHotEncoder()
oh_labels = oh_encoder.fit_transform(labels)

In [67]:
oh_encoder.categories

'auto'

In [68]:
oh_encoder.categories_

[array([0, 1, 2, 3, 4, 5], dtype=int64)]

In [69]:
oh_encoder.sparse

True

In [70]:
oh_encoder

OneHotEncoder()

In [71]:
oh_labels

<8x6 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [72]:
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

#### 판다스 라이브러리를 이용한 인코딩

In [78]:
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
df

item
0     TV
1    냉장고
2  전자레인지
3    컴퓨터
4    선풍기
5    선풍기
6     믹서
7     믹서

In [80]:
pd.get_dummies(df).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)